name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes from GitHub
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.252.240.132 "cd /BiteScout && git pull"

      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.252.240.132 "cd /BiteScout && npm install"

      - name: Restart application
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.252.240.132 "pm2 restart 0"
